ALTER TABLE M_Vilage;

insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(1,true,'-',1,'Suak Indrapuri');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(2,true,'-',1,'Panggong');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(3,true,'-',1,'Kampung Belakang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(4,true,'-',1,'Ujung Kalak');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(5,true,'-',1,'Ujong Baroh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(6,true,'-',1,'Rundeng');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(7,true,'-',1,'Kuta Padang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(8,true,'-',1,'Drien Rampak');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(9,true,'-',1,'Gampong Darat');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(10,true,'-',1,'Gampong Gampa');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(11,true,'-',1,'Seuneubok');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(12,true,'-',1,'Suak Ribee');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(13,true,'-',1,'Suak Raya');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(14,true,'-',1,'Suak Nie');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(15,true,'-',1,'Lapang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(16,true,'-',1,'Leuhan');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(17,true,'-',1,'Blang Beurandang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(18,true,'-',1,'Suak Sigadeng');

insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(19,true,'-',2,'Suak Pante Breuh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(20,true,'-',2,'Suak Seukee');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(21,true,'-',2,'Suak Pandan');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(22,true,'-',2,'Lhok Bubon');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(23,true,'-',2,'Gampong Teungoh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(24,true,'-',2,'Suak Timah');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(25,true,'-',2,'Cot Darat');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(26,true,'-',2,'Pucok Lueng');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(27,true,'-',2,'Alue Raya');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(28,true,'-',2,'Cot Pluh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(29,true,'-',2,'Cot Mesjid');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(30,true,'-',2,'Cot Seulamat');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(31,true,'-',2,'Cot Seumeureng');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(32,true,'-',2,'Paya Lumpat');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(33,true,'-',2,'Ujong Nga');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(34,true,'-',2,'Gampong Ladang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(35,true,'-',2,'Cot Lampise');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(36,true,'-',2,'Pinem');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(37,true,'-',2,'Rangkileh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(38,true,'-',2,'Cot Amun');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(39,true,'-',2,'Reusak');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(40,true,'-',2,'Deuah');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(41,true,'-',2,'Mesjid Baro');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(42,true,'-',2,'Leukeun');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(43,true,'-',2,'Lubok');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(44,true,'-',2,'Krueng Tinggai');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(45,true,'-',2,'Pange');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(46,true,'-',2,'Keureuseng');

insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(47,true,'-',3,'Rambong');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(48,true,'-',3,'Beurawang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(49,true,'-',3,'Kuta Padang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(50,true,'-',3,'Layung');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(51,true,'-',3,'Alue Bakong');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(52,true,'-',3,'Alue Lhok');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(53,true,'-',3,'Gunong Panah');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(54,true,'-',3,'Seumuleng');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(55,true,'-',3,'Kuala Pling');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(56,true,'-',3,'Ulee Blang');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(57,true,'-',3,'Seuneubok Trap');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(58,true,'-',3,'Liceh');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(59,true,'-',3,'Cot Keumuneng');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(60,true,'-',3,'Suak Pangkat');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(61,true,'-',3,'Peulanteu Sp');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(62,true,'-',3,'Cot Lada');
insert into M_Vilage (id,statusEnabled,description,districtId,vilage) values(63,true,'-',3,'Blang Sibeutong');

ALTER TABLE M_Vilage;